#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$DATASTORE_READONLY_USER" NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '$DATASTORE_READONLY_PASSWORD';
    CREATE DATABASE "$DATASTORE_DB" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';
    CREATE ROLE datapusher SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$DATAPUSHER_PASSWORD';
    GRANT CREATE, CONNECT, TEMPORARY ON DATABASE datastore TO datapusher;
    ALTER ROLE datapusher WITH SUPERUSER;
    GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO datapusher;

    -- Créer l'utilisateur
    CREATE ROLE datapusher_jobs WITH LOGIN PASSWORD 'your_password' NOSUPERUSER NOCREATEDB NOCREATEROLE;

    -- Créer la base de données et l'assigner à cet utilisateur
    CREATE DATABASE datapusher_jobs OWNER datapusher_jobs ENCODING 'UTF8';
EOSQL